version: '2'
services:
  jod:  
    image: guilhermeadc/sei3_jod-2.2.2:${ENVIRONMENT_VERSION}
    container_name: jod

  smtp:
    image: guilhermeadc/sei3_mailcatcher:${ENVIRONMENT_VERSION}
    container_name: smtp
    ports:
      - "1080:1080"

  memcached:
    image: guilhermeadc/sei3_memcached:${ENVIRONMENT_VERSION}
    container_name: memcached
    ports:
      - "11211:11211"

  database:
    image: ${DATABASE_IMAGE}:${ENVIRONMENT_VERSION}
    container_name: ${DATABASE_HOST}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ${DATABASE_HOST}:${DATABASE_DATA_DIR}
      - /var/sei/${DATABASE_HOST}/backup:/backup

  solr:
    image: guilhermeadc/sei3_solr-6.1:${ENVIRONMENT_VERSION}
    container_name: solr
    ports:
      - "8983:8983"

  http:
    image: raphaeljpb/sei-tre-pe:latest
    container_name: http
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on: 
      - database
    environment:
      - XDEBUG_CONFIG="idekey=default remote_enable=1 remote_mode=req remote_port=9000 remote_host=10.0.2.2 remote_connect_back=1"
      - HOST_URL=http://localhost:8080
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}

      - SEI_DATABASE_NAME=${SEI_DATABASE_NAME}
      - SEI_DATABASE_USER=${SEI_DATABASE_USER}
      - SEI_DATABASE_PASSWORD=${SEI_DATABASE_PASSWORD}
      - SEI_DATABASE_USER_SCRIPT=${SEI_DATABASE_USER_SCRIPT}
      - SEI_DATABASE_PASSWORD_SCRIPT=${SEI_DATABASE_PASSWORD_SCRIPT}
      
      - SIP_DATABASE_NAME=${SIP_DATABASE_NAME}
      - SIP_DATABASE_USER=${SIP_DATABASE_USER}
      - SIP_DATABASE_PASSWORD=${SIP_DATABASE_PASSWORD}
      - SIP_DATABASE_USER_SCRIPT=${SIP_DATABASE_USER_SCRIPT}
      - SIP_DATABASE_PASSWORD_SCRIPT=${SIP_DATABASE_PASSWORD_SCRIPT}
    links:
      - database:${DATABASE_HOST}
      - memcached:memcachedDATABASE_HEALTHCHECK=
      - solr:solr
      - smtp:smtp
      - jod:jod


volumes:
  mysql:
  oracle:
  sqlserver: